from collections.abc import Callable
from dataclasses import dataclass

import numpy as np


@dataclass
class Metric:
    """Defines a quantification metric.

    Attributes:
        name: The user-facing name of the metric (e.g., 'mean', 'median').
              This will be used in the output column names.
        func: The property name (str) or callable function to be passed to
              skimage.measure.regionprops_table.
    """

    name: str
    func: str | Callable

    @property
    def is_extra(self) -> bool:
        """Returns True if this is a custom function (extra_property)."""
        return callable(self.func)

    @property
    def regionprops_name(self) -> str:
        """Returns the column name generated by regionprops_table for this metric."""
        if self.is_extra:
            return self.func.__name__
        return self.func


METRIC_REGISTRY: dict[str, Metric] = {}


def register_metric(name: str, func: str | Callable) -> None:
    """Registers a new metric."""
    METRIC_REGISTRY[name] = Metric(name, func)


# --- Custom Metric Functions ---


def calculate_median(mask: np.ndarray, intensity_image: np.ndarray) -> float:
    """Calculates the median intensity of the region."""
    return np.median(intensity_image[mask])


def calculate_sum(mask: np.ndarray, intensity_image: np.ndarray) -> float:
    """Calculates the sum intensity of the region."""
    return np.sum(intensity_image[mask])


def calculate_std(mask: np.ndarray, intensity_image: np.ndarray) -> float:
    """Calculates the standard deviation of intensity of the region."""
    return np.std(intensity_image[mask])


# --- Register Default Metrics ---

# Built-in skimage properties
register_metric("mean", "mean_intensity")
register_metric("max", "max_intensity")
register_metric("min", "min_intensity")

# Custom functions
register_metric("median", calculate_median)
register_metric("sum", calculate_sum)
register_metric("std", calculate_std)
