"""Image utilities for reading multiscale images and preparing RGB previews."""

from pathlib import Path

import dask.array as da
import numpy as np
import zarr
from tifffile import TiffFile


def get_org_im_shape(im_path: str | Path) -> tuple[int, int]:
    """Gets the shape of the highest resolution level of an image.

    Args:
        im_path: Path to the image.

    Returns:
        A tuple representing the (height, width) of the image.
    """
    with TiffFile(im_path) as tif:
        width = tif.pages[0].imagewidth
        height = tif.pages[0].imagelength

    return (height, width)


def get_all_resolutions(im_path: str | Path) -> list[da.Array]:
    """Loads all resolution levels from a TIFF file as Dask arrays.

    Args:
        im_path: Path to the TIFF file.

    Returns:
        A list of Dask arrays, one for each resolution level.

    Raises:
        TypeError: If the underlying Zarr object is not an Array or Group.
    """
    # Open the TIFF as a Zarr store (V3 compatible)
    with TiffFile(im_path) as tif:

        store = tif.aszarr()
        # Open the store - could be a Group or an Array
        z_obj = zarr.open(store, mode="r")

        # CASE 1: a single Array (Flat TIFF)
        if isinstance(z_obj, zarr.Array):
            im_list = [da.from_zarr(z_obj)]

        # CASE 2: a Group (Pyramidal TIFF)
        elif isinstance(z_obj, zarr.Group):
            # Find how many levels we actually have
            # Pyramidal TIFFs via tifffile usually have keys '0', '1', '2'...
            available_levels = len(tif.series[0].levels)

            im_list = []
            for level in range(available_levels):
                im_list.append(da.from_zarr(z_obj[str(level)]))

        else:
            raise TypeError(f"Unknown TIFF object type: {type(z_obj)}")

    return im_list


def get_small_image(im_path: str | Path, req_level: int) -> np.ndarray:
    """Gets a specific resolution level from a TIFF file.

    If the file is flat, or the requested resolution level is not available,
    it will be generated by downsampling from the closest available level.

    Args:
        im_path: Path to the TIFF file.
        req_level: Requested resolution level of the image.

    Returns:
        The image at the requested level as a NumPy array.

    Raises:
        TypeError: If the underlying Zarr object is not an Array or Group.
    """
    # Open the TIFF as a Zarr store (V3 compatible)
    with TiffFile(im_path) as tif:
        store = tif.aszarr()
        # Open the store - could be a Group or an Array
        z_obj = zarr.open(store, mode="r")

        # CASE 1: a single Array (Flat TIFF)
        if isinstance(z_obj, zarr.Array):
            im = z_obj[:]
            level_loaded = 0

        # CASE 2: a Group (Pyramidal TIFF)
        elif isinstance(z_obj, zarr.Group):
            # Find how many levels we actually have
            # Pyramidal TIFFs via tifffile usually have keys '0', '1', '2'...
            available_levels = len(tif.series[0].levels)
            level_to_load = min(req_level, available_levels - 1)

            # Access the specific array within the group
            im = z_obj[str(level_to_load)][:]
            level_loaded = level_to_load

        else:
            raise TypeError(f"Unknown TIFF object type: {type(z_obj)}")

        # Final Step: downsample if necessary
        if req_level > level_loaded:
            # strided slicing for speed
            skip = 2 ** (req_level - level_loaded)
            im = im[..., ::skip, ::skip]

    return im


def prepare_rgb_image(
    im_path: str | Path,
    int_min: float | None = None,
    int_max: float | None = None,
    req_level: int = 0,
) -> np.ndarray:
    """Prepares an RGB preview image with stretched intensity.

    Args:
        im_path: Path to the image.
        int_min: Lower intensity threshold for stretching. If None, the
            minimum intensity of the image is used.
        int_max: Upper intensity threshold for stretching. If None, the
            maximum intensity of the image is used.
        req_level: The resolution level to use for the preview.

    Returns:
        The RGB image as an 8-bit NumPy array.
    """
    # get the image of requested resolution
    im = get_small_image(im_path, req_level)

    # rescale between intensities
    if int_min is None:
        int_min = np.min(im)
    if int_max is None:
        int_max = np.max(im)

    im = (im - int_min) / (int_max - int_min)
    im = np.clip(im, 0, 1)

    im = (im * 255).astype(np.uint8)  # change to 8 bit

    # convert to RGB
    im_rgb = np.stack((im,) * 3, axis=-1)

    return im_rgb
